### ISSUE TITLE
Add phpspec to requirements.

### ISSUE THREAD

**Issue by discordier** [phpcq/all-tasks#1]
In https://github.com/contao-community-alliance/build-system/commit/5f440c98d6dc12cba4c1cfd3c60f3baaeb132601 we introduced `phpspec`. This should be added to the list of requirements.

**Comment by discordier** [comment]
I came to the conclusion that it might be better to only add it to the suggest section.
I rarely know any person using it.
What do you think @tristanlins, @stefanheimes? /cc @dmolineus

**Comment by tristanlins** [comment]
phpspec as a standard tool, even if the tool is used rarely. +1 for adding it as requirement.

**Comment by dmolineus** [comment]
+1 for adding it as requirement. Even though if no specs are defined the build tool shouldn't fail. I also vote for a same behaviour for phpunit. I would appreciate if the build task does not fail when no unit tests are defined. At the moment it does.

**Comment by discordier** [comment]
When no unit tests are defined, phpunit does exit with non zero exit code, there is nothing we can do about this.
I have no idea how we should find out if there are tests defined or not. Same for phpspec, I have absolutely no clue about this task and can not provide input here.

**Comment by discordier** [comment]
Has been fixed with: 8d6a049c7f80d1e9ed473c124ddabff8c139462f and phpcq/phpcq@8f79d3671a1ae9eeaefcb9848f05bc9ad5a17203
